import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { History } from "lucide-react";

const labels: Record<string, string> = { "auth.login": "Início de sessão", "tenant.created": "Organização criada", "member.invited": "Convite criado", "member.invitation_accepted": "Convite aceite", "member.updated": "Membro atualizado", "document.uploaded": "Documento carregado", "document.metadata_updated": "Metadados atualizados", "document.approved": "Documento aprovado", "folder_rule.created": "Regra criada", "folder_rule.deleted": "Regra removida", "bank_template.saved": "Modelo de extrato guardado", "bank_import.completed": "Extrato importado", "reconciliation.generated": "Sugestões geradas", "reconciliation.accepted": "Conciliação aceite", "reconciliation.rejected": "Conciliação rejeitada", "integration.prepared": "Integração preparada", "integration.stub_run": "Stub de integração executado" };

export default function AuditPage() {
  const audit = trpc.tenant.audit.useQuery();
  return <div className="mx-auto max-w-5xl space-y-6 px-1 py-3 md:px-5 md:py-6"><header><p className="text-sm font-medium text-teal-700">Rastreabilidade por tenant</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Auditoria</h1><p className="mt-2 text-sm text-slate-500">Registo cronológico das ações críticas realizadas na organização ativa.</p></header><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><History className="h-5 w-5 text-teal-700" />Eventos recentes</CardTitle><CardDescription>Os metadados operacionais são preservados sem incluir os ficheiros originais.</CardDescription></CardHeader><CardContent>{audit.isLoading ? <p className="py-12 text-center text-sm text-slate-500">A carregar auditoria…</p> : audit.data?.length ? <ol className="relative ml-2 border-l border-slate-200">{audit.data.map(event => <li key={event.id} className="relative pb-6 pl-6 last:pb-0"><span className="absolute -left-1.5 top-1.5 h-3 w-3 rounded-full border-2 border-white bg-teal-600" /><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-slate-800">{labels[event.action] ?? event.action}</p><Badge variant="secondary" className="bg-slate-100 text-slate-600">{event.resourceType}</Badge></div><p className="mt-1 text-xs text-slate-500">{new Date(event.createdAt).toLocaleString("pt-PT")}{event.resourceId ? ` · #${event.resourceId}` : ""}</p></li>)}</ol> : <p className="py-12 text-center text-sm text-slate-500">Ainda não existem eventos para apresentar.</p>}</CardContent></Card></div>;
}
