import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CircleDashed, PlugZap, Settings2 } from "lucide-react";
import { toast } from "sonner";

export default function IntegrationsPage() {
  const utils = trpc.useUtils();
  const integrations = trpc.integrations.list.useQuery();
  const prepare = trpc.integrations.prepare.useMutation({ onSuccess: () => { toast.success("Estrutura do conector preparada.", { description: "As credenciais serão adicionadas numa fase de ligação segura." }); utils.integrations.list.invalidate(); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-7xl space-y-6 px-1 py-3 md:px-5 md:py-6"><header><p className="text-sm font-medium text-teal-700">Conectores por organização</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Integrações</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Os adaptadores estão isolados do restante domínio, permitindo ligar credenciais e sincronizações futuras sem alterar documentos ou conciliações.</p></header><div className="grid gap-5 md:grid-cols-3">{integrations.isLoading ? <p className="text-sm text-slate-500">A carregar conectores…</p> : integrations.data?.map(integration => <Card key={integration.provider} className="flex flex-col border-slate-200 shadow-sm"><CardHeader><div className="flex items-start justify-between"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><PlugZap className="h-5 w-5" /></div><Badge variant="secondary" className="bg-slate-100 text-slate-600">{integration.connection ? "Preparada" : "Por configurar"}</Badge></div><CardTitle className="mt-4 text-lg">{integration.label}</CardTitle><CardDescription className="leading-6">{integration.description}</CardDescription></CardHeader><CardContent className="mt-auto space-y-4"><div className="flex flex-wrap gap-1.5">{integration.capabilities.map(capability => <span key={capability} className="rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-600">{capability}</span>)}</div><Button variant="outline" className="w-full" disabled={prepare.isPending} onClick={() => prepare.mutate({ provider: integration.provider })}>{integration.connection ? <CheckCircle2 className="mr-2 h-4 w-4 text-emerald-600" /> : <Settings2 className="mr-2 h-4 w-4" />}{integration.connection ? "Estrutura preparada" : "Preparar conector"}</Button></CardContent></Card>)}</div><Card className="border-amber-200 bg-amber-50/50"><CardContent className="flex gap-3 p-5 text-sm text-amber-900"><CircleDashed className="mt-0.5 h-5 w-5 shrink-0" /><p>Os conectores desta versão são stubs estruturais. A sincronização real e o endpoint de callback serão ativados após disponibilizar as credenciais e especificações de cada fornecedor.</p></CardContent></Card></div>;
}
