import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, CloudCog, ExternalLink, FileDown, Mail, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const labels: Record<string, string> = { nao_configurada: "Não configurada", autorizada: "Autorizada", expirada: "Ligação expirada", erro: "Com erro", desligada: "Desligada" };
const attachmentKey = (item: { messageId: string; attachmentId: string }) => `${item.messageId}:${item.attachmentId}`;

export default function OutlookPage() {
  const [previewRequested, setPreviewRequested] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const status = trpc.outlook.status.useQuery();
  const imports = trpc.outlook.imports.useQuery();
  const preview = trpc.outlook.previewMessages.useQuery(undefined, { enabled: Boolean(status.data?.connection) && previewRequested });
  const begin = trpc.outlook.beginAuthorization.useMutation({ onSuccess: data => window.location.assign(data.url), onError: error => toast.error(error.message) });
  const importSelected = trpc.outlook.importAttachments.useMutation({ onSuccess: data => { const imported = data.results.filter(item => item.status === "imported").length; const duplicates = data.results.filter(item => item.status === "duplicate").length; toast.success(`${imported} documento(s) importado(s)${duplicates ? `; ${duplicates} duplicado(s) ignorado(s)` : ""}.`); imports.refetch(); preview.refetch(); setSelected([]); }, onError: error => toast.error(error.message) });
  const connection = status.data?.connection;
  const attachments = preview.data ?? [];
  const selectAll = () => setSelected(current => current.length === attachments.length ? [] : attachments.map(attachmentKey));
  const toggle = (key: string) => setSelected(current => current.includes(key) ? current.filter(item => item !== key) : [...current, key]);
  const importItems = attachments.filter(item => selected.includes(attachmentKey(item))).map(item => ({ messageId: item.messageId, attachmentId: item.attachmentId }));

  return <div className="mx-auto max-w-6xl space-y-6 px-1 py-3 md:px-5 md:py-6">
    <header className="docuflux-page-heading"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700">Canal documental</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Microsoft 365 / Outlook</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Ligue uma caixa de correio da organização para pré-visualizar e importar anexos documentais para a Inbox, mantendo a aprovação e OCR do DocuFlux.</p></header>
    {!status.data?.environmentReady ? <Alert className="border-amber-200 bg-amber-50 text-amber-950"><TriangleAlert className="h-4 w-4" /><AlertTitle>Configuração Microsoft pendente</AlertTitle><AlertDescription>Faltam as variáveis seguras: <strong>{status.data?.missingEnvironment.join(", ")}</strong>. A ligação não pode ser iniciada até estas credenciais serem configuradas no servidor.</AlertDescription></Alert> : null}
    <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]">
      <Card className="border-emerald-100 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><Mail className="h-5 w-5 text-emerald-700" />Ligação de caixa de correio</CardTitle><CardDescription>A autorização usa Microsoft Graph com leitura delegada, sem enviar nem alterar mensagens.</CardDescription></CardHeader><CardContent className="space-y-5">
        {connection ? <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-slate-900">{connection.mailboxAddress}</p><p className="mt-1 text-xs text-slate-500">Última importação: {connection.lastImportedAt ? new Date(connection.lastImportedAt).toLocaleString("pt-PT") : "ainda não efetuada"}</p></div><Badge className={connection.status === "autorizada" ? "bg-emerald-100 text-emerald-800 hover:bg-emerald-100" : "bg-slate-100 text-slate-700 hover:bg-slate-100"}>{labels[connection.status] ?? connection.status}</Badge></div></div> : <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-7 text-center"><CloudCog className="mx-auto h-7 w-7 text-slate-400" /><p className="mt-3 font-medium text-slate-800">Nenhuma caixa Outlook ligada</p><p className="mt-1 text-sm text-slate-500">Um administrador pode autorizar a conta Microsoft 365 da organização.</p></div>}
        <div className="flex flex-wrap gap-3"><Button disabled={!status.data?.environmentReady || begin.isPending} onClick={() => begin.mutate()}>{connection ? "Renovar autorização" : "Ligar Microsoft 365"}<ExternalLink className="ml-2 h-4 w-4" /></Button><Button variant="outline" disabled={!connection || connection.status !== "autorizada" || preview.isFetching} onClick={() => { setPreviewRequested(true); preview.refetch(); }}><RefreshCw className="mr-2 h-4 w-4" />Pré-visualizar anexos</Button></div>
      </CardContent></Card>
      <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-emerald-700" />Proteções aplicadas</CardTitle></CardHeader><CardContent><ul className="space-y-3 text-sm text-slate-600"><li className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />Leitura delegada limitada à conta que autorizou.</li><li className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />Tokens de renovação cifrados no servidor.</li><li className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />Apenas PDF, JPG, PNG e DOCX até 10 MB são elegíveis.</li><li className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />Duplicados por hash são ignorados e cada execução fica auditada.</li></ul></CardContent></Card>
    </div>
    {previewRequested ? <Card className="border-slate-200 shadow-sm"><CardHeader className="flex flex-row items-center justify-between gap-4"><div><CardTitle>Anexos elegíveis</CardTitle><CardDescription>Selecione no máximo 20 anexos; as mensagens não são movidas, marcadas nem alteradas.</CardDescription></div>{attachments.length ? <Button variant="outline" size="sm" onClick={selectAll}>{selected.length === attachments.length ? "Limpar seleção" : "Selecionar todos"}</Button> : null}</CardHeader><CardContent>{preview.isLoading || preview.isFetching ? <p className="py-8 text-center text-sm text-slate-500">A consultar a caixa Outlook…</p> : preview.isError ? <Alert variant="destructive"><TriangleAlert className="h-4 w-4" /><AlertTitle>Não foi possível consultar os anexos</AlertTitle><AlertDescription>{preview.error.message}</AlertDescription></Alert> : attachments.length ? <div className="space-y-2">{attachments.map(item => { const key = attachmentKey(item); return <label key={key} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 transition-colors hover:bg-slate-50"><Checkbox checked={selected.includes(key)} onCheckedChange={() => toggle(key)} aria-label={`Selecionar ${item.filename}`} /><FileDown className="h-4 w-4 shrink-0 text-emerald-700" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{item.filename}</p><p className="mt-0.5 truncate text-xs text-slate-500">{item.subject} · {item.fromAddress ?? "Remetente indisponível"} · {(item.size / 1024 / 1024).toFixed(2)} MB</p></div><Badge variant="secondary">{item.contentType === "application/pdf" ? "PDF" : item.contentType.split("/").at(-1)?.toUpperCase()}</Badge></label>; })}<div className="flex items-center justify-between border-t border-slate-100 pt-4"><p className="text-sm text-slate-600">{selected.length} selecionado(s)</p><Button disabled={!selected.length || importSelected.isPending} onClick={() => importSelected.mutate({ attachments: importItems })}>Importar para a Inbox</Button></div></div> : <p className="py-8 text-center text-sm text-slate-500">Não foram encontrados anexos elegíveis nas mensagens recentes.</p>}</CardContent></Card> : null}
    <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Histórico de importações</CardTitle><CardDescription>Execuções por organização; o processamento de OCR começa depois de cada documento ser guardado na Inbox.</CardDescription></CardHeader><CardContent>{imports.data?.length ? <div className="space-y-3">{imports.data.map(run => <div key={run.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="font-medium text-slate-800">Importação Outlook</p><p className="mt-1 text-xs text-slate-500">{new Date(run.startedAt).toLocaleString("pt-PT")} · {run.messageCount} mensagens · {run.attachmentCount} anexos · {run.importedDocumentCount} documentos</p></div><Badge variant="secondary">{run.status}</Badge></div>)}</div> : <p className="py-10 text-center text-sm text-slate-500">Ainda não existem importações Outlook nesta organização.</p>}</CardContent></Card>
  </div>;
}
