import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Loader2, Plus, RefreshCw, WalletCards } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const monthNames = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
const weekDays = ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"];
function dateKey(year: number, month: number, day: number) { return `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; }
function formatMoney(cents: number, currency = "EUR") { return new Intl.NumberFormat("pt-PT", { style: "currency", currency }).format(cents / 100); }
function cents(value: string) { return Math.round(Number(value.replace(",", ".")) * 100); }

export default function PaymentsPage() {
  const now = new Date();
  const [year, setYear] = useState(now.getFullYear()); const [month, setMonth] = useState(now.getMonth());
  const [dialogOpen, setDialogOpen] = useState(false); const [counterparty, setCounterparty] = useState(""); const [dueDate, setDueDate] = useState(""); const [amount, setAmount] = useState(""); const [notes, setNotes] = useState("");
  const utils = trpc.useUtils();
  const payments = trpc.payments.list.useQuery();
  const create = trpc.payments.create.useMutation({ onSuccess: () => { toast.success("Pagamento criado."); setDialogOpen(false); setCounterparty(""); setDueDate(""); setAmount(""); setNotes(""); utils.payments.list.invalidate(); }, onError: error => toast.error(error.message) });
  const updateStatus = trpc.payments.updateStatus.useMutation({ onSuccess: () => { toast.success("Estado do pagamento atualizado."); utils.payments.list.invalidate(); }, onError: error => toast.error(error.message) });
  const syncDocuments = trpc.payments.syncDocuments.useMutation({ onSuccess: result => { toast.success("Calendário sincronizado.", { description: `${result.synced} fatura(s) recebida(s) atualizada(s).` }); utils.payments.list.invalidate(); }, onError: error => toast.error(error.message) });
  const monthPayments = useMemo(() => payments.data?.filter(item => { const [itemYear, itemMonth] = item.dueDate.split("-").map(Number); return itemYear === year && itemMonth === month + 1; }) ?? [], [payments.data, year, month]);
  const byDate = useMemo(() => { const map = new Map<string, typeof monthPayments>(); for (const item of monthPayments) map.set(item.dueDate, [...(map.get(item.dueDate) ?? []), item]); return map; }, [monthPayments]);
  const pending = payments.data?.filter(item => item.status === "pendente") ?? []; const today = new Date().toISOString().slice(0, 10); const overdue = pending.filter(item => item.dueDate < today); const dueTotal = monthPayments.filter(item => item.status === "pendente").reduce((sum, item) => sum + item.amountCents, 0); const overdueTotal = overdue.reduce((sum, item) => sum + item.amountCents, 0);
  const firstDay = (new Date(year, month, 1).getDay() + 6) % 7; const days = new Date(year, month + 1, 0).getDate(); const cells = Array.from({ length: Math.ceil((firstDay + days) / 7) * 7 }, (_, index) => index - firstDay + 1);
  const shiftMonth = (delta: number) => { const target = new Date(year, month + delta, 1); setYear(target.getFullYear()); setMonth(target.getMonth()); };

  return <div className="mx-auto max-w-7xl space-y-6 px-1 py-3 md:px-5 md:py-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-teal-700">Tesouraria</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Calendário de pagamentos</h1><p className="mt-2 text-sm text-slate-500">Acompanhe vencimentos, crie pagamentos avulsos e confirme liquidações por organização.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Button variant="outline" disabled={syncDocuments.isPending} onClick={() => syncDocuments.mutate()}>{syncDocuments.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <RefreshCw className="mr-2 h-4 w-4" />}Sincronizar faturas</Button><Button className="bg-teal-700 hover:bg-teal-800" onClick={() => setDialogOpen(true)}><Plus className="mr-2 h-4 w-4" />Novo pagamento</Button></div></header>
    <div className="grid gap-4 md:grid-cols-3"><SummaryCard label="A vencer no mês" value={formatMoney(dueTotal)} description={`${monthPayments.filter(item => item.status === "pendente").length} pagamento(s) pendente(s)`} icon={WalletCards} tone="teal" /><SummaryCard label="Em atraso" value={formatMoney(overdueTotal)} description={`${overdue.length} vencimento(s) anterior(es) a hoje`} icon={CircleAlert} tone="amber" /><SummaryCard label="Pagos este mês" value={formatMoney(monthPayments.filter(item => item.status === "pago").reduce((sum, item) => sum + item.amountCents, 0))} description={`${monthPayments.filter(item => item.status === "pago").length} pagamento(s) confirmado(s)`} icon={CheckCircle2} tone="green" /></div>
    <Card className="border-slate-200 shadow-sm"><CardHeader><div className="flex items-center justify-between"><Button variant="outline" size="icon" aria-label="Mês anterior" onClick={() => shiftMonth(-1)}><ChevronLeft className="h-4 w-4" /></Button><div className="text-center"><CardTitle className="text-xl">{monthNames[month]} de {year}</CardTitle><CardDescription className="mt-1">Clique num vencimento para consultar ou confirmar o pagamento.</CardDescription></div><Button variant="outline" size="icon" aria-label="Mês seguinte" onClick={() => shiftMonth(1)}><ChevronRight className="h-4 w-4" /></Button></div></CardHeader><CardContent><div className="grid grid-cols-7 border-l border-t border-slate-200">{weekDays.map(day => <div key={day} className="border-b border-r border-slate-200 bg-slate-50 px-2 py-2 text-center text-xs font-medium text-slate-500">{day}</div>)}{cells.map((day, index) => { if (day < 1 || day > days) return <div key={index} className="min-h-28 border-b border-r border-slate-200 bg-slate-50/50" />; const key = dateKey(year, month, day); const items = byDate.get(key) ?? []; const isToday = key === today; return <div key={key} className="min-h-28 border-b border-r border-slate-200 p-2"><p className={`mb-2 flex h-6 w-6 items-center justify-center rounded-full text-xs font-medium ${isToday ? "bg-teal-700 text-white" : "text-slate-600"}`}>{day}</p><div className="space-y-1">{items.slice(0, 3).map(item => <button key={item.id} className={`block w-full truncate rounded px-1.5 py-1 text-left text-[11px] font-medium ${item.status === "pago" ? "bg-emerald-50 text-emerald-700 line-through" : item.dueDate < today ? "bg-red-50 text-red-700" : "bg-teal-50 text-teal-800"}`} title={`${item.counterparty} · ${formatMoney(item.amountCents, item.currency)}`} onClick={() => item.status === "pendente" && updateStatus.mutate({ id: item.id, status: "pago" })}>{item.counterparty} · {formatMoney(item.amountCents, item.currency)}</button>)}{items.length > 3 && <p className="text-[11px] text-slate-400">+{items.length - 3} pagamento(s)</p>}</div></div>; })}</div></CardContent></Card>
    <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-5 w-5 text-teal-700" />Próximos vencimentos</CardTitle><CardDescription>Confirme um pagamento assim que a liquidação estiver registada no banco.</CardDescription></CardHeader><CardContent>{pending.length ? <div className="divide-y divide-slate-100">{pending.slice(0, 12).map(item => <div className="flex flex-col gap-3 py-3 sm:flex-row sm:items-center sm:justify-between" key={item.id}><div><p className="font-medium text-slate-800">{item.counterparty}</p><p className="mt-1 text-xs text-slate-500">Vencimento: {new Date(`${item.dueDate}T00:00:00`).toLocaleDateString("pt-PT")}{item.notes ? ` · ${item.notes}` : ""}</p></div><div className="flex items-center gap-3"><span className="font-semibold text-slate-800">{formatMoney(item.amountCents, item.currency)}</span><Badge className={item.dueDate < today ? "bg-red-100 text-red-700 hover:bg-red-100" : "bg-amber-100 text-amber-800 hover:bg-amber-100"}>{item.dueDate < today ? "Em atraso" : "Pendente"}</Badge><Button size="sm" variant="outline" disabled={updateStatus.isPending} onClick={() => updateStatus.mutate({ id: item.id, status: "pago" })}><CheckCircle2 className="mr-2 h-4 w-4" />Marcar pago</Button></div></div>)}</div> : <div className="py-12 text-center"><CalendarDays className="mx-auto h-9 w-9 text-slate-300" /><p className="mt-3 font-medium text-slate-700">Não existem pagamentos pendentes</p><p className="mt-1 text-sm text-slate-500">Sincronize as faturas recebidas ou crie um pagamento manualmente.</p></div>}</CardContent></Card>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent><DialogHeader><DialogTitle>Novo pagamento</DialogTitle><DialogDescription>Crie um vencimento que não esteja associado a um documento.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Credor ou fornecedor</Label><Input value={counterparty} onChange={event => setCounterparty(event.target.value)} placeholder="Ex.: Vodafone Portugal" /></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Data de vencimento</Label><Input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} /></div><div className="space-y-2"><Label>Valor (€)</Label><Input inputMode="decimal" value={amount} onChange={event => setAmount(event.target.value)} placeholder="0,00" /></div></div><div className="space-y-2"><Label>Notas</Label><Textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Referência ou contexto opcional" /></div></div><DialogFooter><Button variant="outline" onClick={() => setDialogOpen(false)}>Cancelar</Button><Button className="bg-teal-700 hover:bg-teal-800" disabled={create.isPending} onClick={() => { const amountCents = cents(amount); if (!counterparty.trim() || !dueDate || !Number.isFinite(amountCents) || amountCents <= 0) return toast.error("Preencha credor, vencimento e valor válido."); create.mutate({ counterparty: counterparty.trim(), dueDate, amountCents, notes: notes || undefined }); }}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Criar pagamento</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function SummaryCard({ label, value, description, icon: Icon, tone }: { label: string; value: string; description: string; icon: typeof WalletCards; tone: "teal" | "amber" | "green" }) { const tones = { teal: "bg-teal-50 text-teal-700", amber: "bg-amber-50 text-amber-700", green: "bg-emerald-50 text-emerald-700" }; return <Card className="border-slate-200 shadow-sm"><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div><div className={`rounded-xl p-2.5 ${tones[tone]}`}><Icon className="h-5 w-5" /></div></CardContent></Card>; }
