import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FileSearch, Loader2, ReceiptText, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type TaxCategory = "alimentacao" | "combustivel" | "utilidades" | "outro";
const categoryLabel: Record<TaxCategory, string> = { alimentacao: "Alimentação e bebidas", combustivel: "Combustível", utilidades: "Água, eletricidade ou telecomunicações", outro: "Outra despesa / requer revisão" };
const statusLabel: Record<string, string> = { pendente: "Pendente de contabilista", confirmado_contabilista: "Confirmado", excecao: "Exceção registada", rejeitado: "Rejeitado" };
const statusClass: Record<string, string> = { pendente: "bg-amber-100 text-amber-800", confirmado_contabilista: "bg-emerald-100 text-emerald-800", excecao: "bg-sky-100 text-sky-800", rejeitado: "bg-slate-100 text-slate-700" };
function money(cents: number | null | undefined) { return cents === null || cents === undefined ? "A confirmar" : new Intl.NumberFormat("pt-PT", { style: "currency", currency: "EUR" }).format(cents / 100); }
function eurosToCents(value: string) { const amount = Number(value.replace(",", ".")); return Number.isFinite(amount) && amount >= 0 ? Math.round(amount * 100) : null; }

export default function TaxReviewPage() {
  const utils = trpc.useUtils();
  const documents = trpc.documents.list.useQuery();
  const proposals = trpc.taxReview.list.useQuery();
  const [categories, setCategories] = useState<Record<number, TaxCategory>>({});
  const [values, setValues] = useState<Record<number, { deductible: string; nonDeductible: string }>>({});
  const propose = trpc.taxReview.propose.useMutation({ onSuccess: () => { toast.success("Proposta de IVA criada para confirmação profissional."); utils.taxReview.list.invalidate(); }, onError: error => toast.error(error.message) });
  const confirm = trpc.taxReview.confirm.useMutation({ onSuccess: () => { toast.success("Revisão fiscal confirmada e auditada."); utils.taxReview.list.invalidate(); }, onError: error => toast.error(error.message) });
  const proposalByDocument = useMemo(() => new Map((proposals.data ?? []).map(item => [item.document.id, item.proposal])), [proposals.data]);
  const eligible = useMemo(() => (documents.data ?? []).filter(document => document.documentType === "fatura_recebida" && document.status !== "novo" && document.vatCents !== null), [documents.data]);
  const getValues = (proposal: { id: number; vatDeductibleCents: number | null; vatNonDeductibleCents: number | null }) => values[proposal.id] ?? { deductible: proposal.vatDeductibleCents === null ? "" : (proposal.vatDeductibleCents / 100).toFixed(2), nonDeductible: proposal.vatNonDeductibleCents === null ? "" : (proposal.vatNonDeductibleCents / 100).toFixed(2) };

  return <div className="docuflux-page mx-auto max-w-7xl space-y-6 px-1 py-3 md:px-5 md:py-6"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-medium text-teal-700">Contabilidade assistida</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Revisão de IVA</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">O DocuFlux preserva o IVA original e apenas propõe um tratamento por categoria. A confirmação do contabilista é obrigatória antes de qualquer exportação.</p></div><Badge className="w-fit bg-amber-100 text-amber-800 hover:bg-amber-100"><ShieldCheck className="mr-1.5 h-3.5 w-3.5" />Sem declaração nem exportação automática</Badge></header>
    <Card className="border-amber-200 bg-amber-50/50 shadow-sm"><CardContent className="flex gap-3 p-5"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-700" /><div><p className="font-medium text-amber-950">Proposta fiscal, não decisão automática</p><p className="mt-1 text-sm text-amber-900">Para alimentação, a proposta inicial é IVA não dedutível, salvo exceção. Para combustível, o sistema não assume percentagem: pede confirmação do tipo de combustível, veículo e uso. Esta funcionalidade não preenche declarações nem comunica ao TOConline.</p></div></CardContent></Card>
    <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><ReceiptText className="h-5 w-5 text-teal-700" />Faturas com IVA elegíveis</CardTitle><CardDescription>Escolha a categoria para criar ou atualizar uma proposta pendente de confirmação profissional.</CardDescription></CardHeader><CardContent>{documents.isLoading ? <p className="py-8 text-sm text-slate-500">A carregar faturas…</p> : eligible.length ? <div className="divide-y divide-slate-100">{eligible.map(document => { const proposal = proposalByDocument.get(document.id); const category = categories[document.id] ?? "outro"; return <div key={document.id} className="flex flex-col gap-3 py-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-medium text-slate-800">{document.entityName || "Fornecedor por confirmar"} <span className="font-normal text-slate-500">· {document.documentNumber || document.originalFilename}</span></p><p className="mt-1 text-xs text-slate-500">IVA original: {money(document.vatCents)} · {document.documentDate || "Sem data"}</p></div><div className="flex flex-wrap items-center gap-2">{proposal ? <Badge variant="secondary" className={statusClass[proposal.reviewStatus]}>{statusLabel[proposal.reviewStatus]}</Badge> : <><select className="h-9 max-w-64 rounded-md border border-input bg-background px-3 text-sm" value={category} onChange={event => setCategories(current => ({ ...current, [document.id]: event.target.value as TaxCategory }))}>{(Object.keys(categoryLabel) as TaxCategory[]).map(value => <option key={value} value={value}>{categoryLabel[value]}</option>)}</select><Button size="sm" variant="outline" disabled={propose.isPending} onClick={() => propose.mutate({ documentId: document.id, taxCategory: category })}>{propose.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <FileSearch className="mr-2 h-4 w-4" />}Propor IVA</Button></>}</div></div>; })}</div> : <p className="py-10 text-center text-sm text-slate-500">Não existem faturas revistas com IVA identificado.</p>}</CardContent></Card>
    <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Confirmação do contabilista</CardTitle><CardDescription>Os valores dedutível e não dedutível devem totalizar exatamente o IVA original. A aprovação fica auditada por fatura.</CardDescription></CardHeader><CardContent>{proposals.isLoading ? <p className="py-8 text-sm text-slate-500">A carregar propostas fiscais…</p> : (proposals.data ?? []).length ? <div className="space-y-3">{proposals.data?.map(({ proposal, document }) => { const current = getValues(proposal); return <div key={proposal.id} className="rounded-xl border border-slate-100 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-medium text-slate-800">{document.entityName || "—"} · {document.documentNumber || document.originalFilename}</p><Badge variant="secondary" className={statusClass[proposal.reviewStatus]}>{statusLabel[proposal.reviewStatus]}</Badge></div><p className="mt-1 text-xs text-slate-500">{categoryLabel[proposal.taxCategory]} · IVA original {money(proposal.vatOriginalCents)} · regra {proposal.ruleCode} v{proposal.ruleVersion}</p><p className="mt-2 max-w-3xl text-sm text-slate-600">{proposal.rationale}</p></div>{proposal.reviewStatus === "pendente" && <div className="grid gap-2 sm:grid-cols-[130px_130px_auto] lg:w-[440px]"><Input inputMode="decimal" aria-label={`IVA dedutível ${proposal.id}`} value={current.deductible} onChange={event => setValues(previous => ({ ...previous, [proposal.id]: { ...current, deductible: event.target.value } }))} placeholder="Dedutível €" /><Input inputMode="decimal" aria-label={`IVA não dedutível ${proposal.id}`} value={current.nonDeductible} onChange={event => setValues(previous => ({ ...previous, [proposal.id]: { ...current, nonDeductible: event.target.value } }))} placeholder="Não dedutível €" /><Button disabled={confirm.isPending} onClick={() => { const deductible = eurosToCents(current.deductible); const nonDeductible = eurosToCents(current.nonDeductible); if (deductible === null || nonDeductible === null) return toast.error("Indique valores de IVA válidos."); confirm.mutate({ documentId: document.id, reviewStatus: "confirmado_contabilista", vatDeductibleCents: deductible, vatNonDeductibleCents: nonDeductible }); }}><CheckCircle2 className="mr-2 h-4 w-4" />Confirmar</Button></div>}</div></div>; })}</div> : <p className="py-10 text-center text-sm text-slate-500">Ainda não existem propostas fiscais para confirmar.</p>}</CardContent></Card>
  </div>;
}
